Fix the sometimes shortened traceback prints when an exception occurrs in a callback function.  Instead of printing the full traceback like this
  Exception: exception message

only the exception class name was printed in this way:

  Exception

The problem was that I was calling
  PyString_ConcatAndDel(&string, newpart)
with newpart not being a Python string.

--HG--
extra : convert_revision : svn%3A6015fed2-1504-0410-9fe1-9d1591cc4771/ctypes/trunk%4048165